elasticsearch:
  image: elasticsearch
  volumes_from:
  - esdata
  ports:
   - "127.0.0.1:9200:9200"
mosquitto:
  image: maxheadroom/owntracks
  ports:
   - "1883:1883"
ubirchserver:
  image: ubirch/ubirch-server
  links:
    - mosquitto:mqtt
    - elasticsearch:search
  volumes:
    - /opt/ubirch-dc-appstack/ubirch-server:/opt
kibana:
   image: kibana
   ports:
    - "127.0.0.1:5601:5601"
   links:
    - elasticsearch:elasticsearch

